apiVersion: v1
kind: Service
metadata:
  name: similarities-python-service
spec:
  selector:
    app: similarities-python
  ports:
  - protocol: "TCP"
    port: 443
    targetPort: 5000
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: similarities-python
spec:
  selector:
    matchLabels:
      app: similarities-python
  replicas: 4
  template:
    metadata:
      labels:
        app: similarities-python
    spec:
      containers:
      - name: similarities-python
        image: similarities-python:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      imagePullSecrets:
      - name: regcred